"""fix_alias_nullable

Revision ID: 643470736319
Revises: f85746e39315
Create Date: 2026-08-27 01:17:43.331126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '643470736319'
down_revision: Union[str, Sequence[str], None] = 'f85746e39315'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'alias',
               existing_type=sa.VARCHAR(length=128),
               nullable=True,
               comment='Optional MCP alias for project resolution',
               existing_comment='MCP alias for project resolution')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'alias',
               existing_type=sa.VARCHAR(length=128),
               nullable=False,
               comment='MCP alias for project resolution',
               existing_comment='Optional MCP alias for project resolution')
    # ### end Alembic commands ###
