"""001_initial

Revision ID: 9d2819c0965c
Revises: 
Create Date: 2026-08-26 23:59:27.043329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9d2819c0965c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_scopes',
    sa.Column('scope_id', sa.Integer(), autoincrement=False, nullable=False, comment='Snowflake ID'),
    sa.Column('scope_type', sa.String(length=16), nullable=False, comment="'project' or 'public'"),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=16), server_default=sa.text("'active'"), nullable=False, comment="'active', 'archived', or 'deleting'"),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('scope_id')
    )
    op.create_table('retrieval_runs',
    sa.Column('run_id', sa.Integer(), autoincrement=False, nullable=False, comment='Snowflake ID'),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('project_scopes', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='List of resolved scope descriptors'),
    sa.Column('completion_status', sa.String(length=16), nullable=False, comment="'complete', 'partial', 'no_evidence', or 'failed'"),
    sa.Column('evidence_count', sa.Integer(), nullable=False, comment='Number of evidence items returned, >= 0'),
    sa.Column('duration_ms', sa.Integer(), nullable=False, comment='Wall-clock retrieval time in ms, >= 0'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("NOW() + INTERVAL '7 days'"), nullable=False, comment='TTL expiry; cleanup task deletes rows past this timestamp'),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_table('knowledge_sources',
    sa.Column('source_id', sa.Integer(), autoincrement=False, nullable=False, comment='Snowflake ID'),
    sa.Column('knowledge_scope_id', sa.BigInteger(), nullable=False),
    sa.Column('filename', sa.String(length=1024), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False, comment='SHA-256 hex digest'),
    sa.Column('format', sa.String(length=16), nullable=False, comment="'markdown' or 'java'"),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False, comment='File size in bytes, >= 0'),
    sa.Column('status', sa.String(length=16), server_default=sa.text("'uploaded'"), nullable=False, comment="'uploaded', 'processing', 'published', 'failed', or 'deleted'"),
    sa.Column('processing_error', sa.Text(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_scope_id'], ['knowledge_scopes.scope_id'], ),
    sa.PrimaryKeyConstraint('source_id')
    )
    op.create_table('knowledge_versions',
    sa.Column('version_id', sa.Integer(), autoincrement=False, nullable=False, comment='Snowflake ID'),
    sa.Column('knowledge_scope_id', sa.BigInteger(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False, comment='Monotonically increasing, > 0'),
    sa.Column('capabilities', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False, comment='Index capability manifest, e.g. {"dense_ready": true}'),
    sa.Column('status', sa.String(length=16), server_default=sa.text("'draft'"), nullable=False, comment="'draft', 'published', or 'superseded'"),
    sa.Column('published_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_scope_id'], ['knowledge_scopes.scope_id'], ),
    sa.PrimaryKeyConstraint('version_id'),
    sa.UniqueConstraint('knowledge_scope_id', 'version_number', name='uq_kv_scope_version')
    )
    op.create_table('projects',
    sa.Column('project_id', sa.Integer(), autoincrement=False, nullable=False, comment='Snowflake ID'),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('alias', sa.String(length=128), nullable=False, comment='MCP alias for project resolution'),
    sa.Column('repo_path', sa.String(length=1024), nullable=True, comment='Optional repository / workspace path'),
    sa.Column('knowledge_scope_id', sa.BigInteger(), nullable=False, comment='1:1 link to the project knowledge scope'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_scope_id'], ['knowledge_scopes.scope_id'], ),
    sa.PrimaryKeyConstraint('project_id'),
    sa.UniqueConstraint('alias'),
    sa.UniqueConstraint('knowledge_scope_id'),
    sa.UniqueConstraint('repo_path')
    )
    op.create_table('chunks',
    sa.Column('chunk_id', sa.Integer(), autoincrement=False, nullable=False, comment='Snowflake ID; also Qdrant Point ID'),
    sa.Column('source_id', sa.BigInteger(), nullable=False),
    sa.Column('version_id', sa.BigInteger(), nullable=False),
    sa.Column('knowledge_scope_id', sa.BigInteger(), nullable=False, comment='Redundant FK for fast scope-filtered queries'),
    sa.Column('parent_chunk_id', sa.BigInteger(), nullable=True, comment='Self-referential; NULL for top-level chunks'),
    sa.Column('content_text', sa.Text(), nullable=False, comment='Credential-sanitized chunk body'),
    sa.Column('position_path', sa.String(length=1024), nullable=False, comment='Section path or fully-qualified symbol path'),
    sa.Column('chunk_type', sa.String(length=16), nullable=False, comment="'section' or 'symbol'"),
    sa.Column('start_line', sa.Integer(), nullable=False, comment='1-based inclusive start line, > 0'),
    sa.Column('end_line', sa.Integer(), nullable=False, comment='1-based inclusive end line, >= start_line'),
    sa.Column('token_count', sa.Integer(), nullable=False, comment='Estimated token count, > 0'),
    sa.Column('embedding_model', sa.String(length=128), nullable=False, comment='Model that generated the embedding'),
    sa.Column('index_version', sa.String(length=64), nullable=False, comment='Composite identifier: embedding model + chunking strategy version'),
    sa.ForeignKeyConstraint(['knowledge_scope_id'], ['knowledge_scopes.scope_id'], ),
    sa.ForeignKeyConstraint(['parent_chunk_id'], ['chunks.chunk_id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['knowledge_sources.source_id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['knowledge_versions.version_id'], ),
    sa.PrimaryKeyConstraint('chunk_id')
    )
    op.create_table('processing_runs',
    sa.Column('run_id', sa.Integer(), autoincrement=False, nullable=False, comment='Snowflake ID'),
    sa.Column('source_id', sa.BigInteger(), nullable=False),
    sa.Column('run_type', sa.String(length=16), nullable=False, comment="'initial' or 'retry'"),
    sa.Column('status', sa.String(length=16), server_default=sa.text("'pending'"), nullable=False, comment="'pending', 'running', 'completed', or 'failed'"),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('stages', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False, comment='Ordered list of stage records'),
    sa.ForeignKeyConstraint(['source_id'], ['knowledge_sources.source_id'], ),
    sa.PrimaryKeyConstraint('run_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('processing_runs')
    op.drop_table('chunks')
    op.drop_table('projects')
    op.drop_table('knowledge_versions')
    op.drop_table('knowledge_sources')
    op.drop_table('retrieval_runs')
    op.drop_table('knowledge_scopes')
    # ### end Alembic commands ###
