"""fix_bigint_columns

Revision ID: f85746e39315
Revises: 9d2819c0965c
Create Date: 2026-08-27 01:16:28.108266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f85746e39315'
down_revision: Union[str, Sequence[str], None] = '9d2819c0965c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chunks', 'chunk_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_comment='Snowflake ID; also Qdrant Point ID',
               existing_nullable=False,
               autoincrement=False)
    op.alter_column('knowledge_scopes', 'scope_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_comment='Snowflake ID',
               existing_nullable=False,
               autoincrement=False)
    op.alter_column('knowledge_sources', 'source_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_comment='Snowflake ID',
               existing_nullable=False,
               autoincrement=False)
    op.alter_column('knowledge_versions', 'version_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_comment='Snowflake ID',
               existing_nullable=False,
               autoincrement=False)
    op.alter_column('processing_runs', 'run_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_comment='Snowflake ID',
               existing_nullable=False,
               autoincrement=False)
    op.alter_column('projects', 'project_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_comment='Snowflake ID',
               existing_nullable=False,
               autoincrement=False)
    op.alter_column('retrieval_runs', 'run_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_comment='Snowflake ID',
               existing_nullable=False,
               autoincrement=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('retrieval_runs', 'run_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_comment='Snowflake ID',
               existing_nullable=False,
               autoincrement=False)
    op.alter_column('projects', 'project_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_comment='Snowflake ID',
               existing_nullable=False,
               autoincrement=False)
    op.alter_column('processing_runs', 'run_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_comment='Snowflake ID',
               existing_nullable=False,
               autoincrement=False)
    op.alter_column('knowledge_versions', 'version_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_comment='Snowflake ID',
               existing_nullable=False,
               autoincrement=False)
    op.alter_column('knowledge_sources', 'source_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_comment='Snowflake ID',
               existing_nullable=False,
               autoincrement=False)
    op.alter_column('knowledge_scopes', 'scope_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_comment='Snowflake ID',
               existing_nullable=False,
               autoincrement=False)
    op.alter_column('chunks', 'chunk_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_comment='Snowflake ID; also Qdrant Point ID',
               existing_nullable=False,
               autoincrement=False)
    # ### end Alembic commands ###
